spring:
  profiles:
    active: dev
  config:
    import: optional:file./.env

logging:
  level:
    root: info
    org.springframework: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    javax.management.remote.rmi: info
    sun.rmi.transport.tcp: info
    sun.rmi.loader: info
    com.zaxxer.hikari: info

discodeit:
  storage:
    type: local
    local:
      root-path: ./storage

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}