spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8080

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
